import { useState, useEffect, useMemo, useCallback } from 'react';
import { SearchInput } from './components/SearchInput';
import { DropdownFilter } from './components/DropdownFilter';
import { ResultCard } from './components/ResultCard';
import { FavoritesList } from './components/FavoritesList';
import { AffiliateItem } from './types';
import { Menu, Search, WifiOff, AlertTriangle, X, Bug, ChevronDown, ChevronUp, Copy, Trash2 } from 'lucide-react';
import { cleanProductName } from './productNameCleaner';
import { PointSettings, loadSettings, calcEffectiveTotal } from './pointSettings';
import { AnimatePresence, motion } from 'motion/react';
import { fetchSearXNG, SearXNGAllDownError } from './utils/searxngClient';
import { mergeSearXNGResults } from './utils/searxngMerger';
import { GoogleLoginButton } from './components/GoogleLoginButton';
import { analyzeProductNameWithGemini } from './geminiService';
